[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.29.0"
ci = "github"
installers = ["shell", "homebrew"]
tap = "vigimite/homebrew-aqueducts"
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
install-path = "CARGO_HOME"
publish-jobs = ["homebrew"]
install-updater = false
bins = ["aqueducts-cli"]
system-dependencies = { homebrew = ["unixodbc", "pkg-config"], apt = "unixodbc-dev" }
features = ["odbc"]

[dist.env]
# Help find ODBC on macOS - handle both ARM64 (/opt/homebrew) and x86_64 (/usr/local)
PKG_CONFIG_PATH = "/opt/homebrew/opt/unixodbc/lib/pkgconfig:/opt/homebrew/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig"
LIBRARY_PATH = "/opt/homebrew/opt/unixodbc/lib:/opt/homebrew/lib:/usr/local/lib:/usr/lib"
DYLD_LIBRARY_PATH = "/opt/homebrew/opt/unixodbc/lib:/opt/homebrew/lib"
MACOSX_DEPLOYMENT_TARGET = "11.0"
PKG_CONFIG_ALLOW_CROSS = "1"

[dist.homebrew]
formula-name = "aqueducts-cli"
