site_name: Aqueducts Documentation
site_url: https://vigimite.github.io/aqueducts
repo_url: https://github.com/vigimite/aqueducts
repo_name: vigimite/aqueducts
copyright: Copyright &copy; 2024 Michele Vigilante
docs_dir: "docs/"

hooks:
  - json_schema/generate_schema_reference.py

nav:
  - Home: index.md
  - Usage: usage.md
  - Storage Configuration: storage.md
  - Schema Reference: schema_reference.md
  - Architecture: architecture.md
  - Aqueducts CLI: cli.md
  - About: about.md

theme:
  language: en
  name: material
  logo: assets/logo.png
  icon: 
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    - navigation.top

    - toc.integrate
    - toc.follow

    - search.suggest

    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

extra:
  generator: true
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@kato
    - icon: fontawesome/brands/github
      link: https://github.com/vigimite

plugins: 
  - search
  - social

markdown_extensions:
  - toc:
      toc_depth: 5
  - tables
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
