blank_issues_enabled: true
contact_links:
  - name: Questions and Help
    url: https://github.com/vigimite/aqueducts/discussions
    about: Please ask and answer questions in the Discussions section
  - name: Documentation
    url: https://vigimite.github.io/aqueducts
    about: Check our documentation for information about usage and configuration