blank_issues_enabled: true
contact_links:
  - name: Questions and Help
    url: https://github.com/vigimite/aqueducts/?tab=readme-ov-file#community
    about: Please ask and answer questions in the Aqueducts discord server
  - name: Documentation
    url: https://vigimite.github.io/aqueducts
    about: Check our documentation for information about usage and configuration
